### 2023.10.19 - Introduction to Transformers | Homework 1
In this exercise, you will implement your own character-based Tokenizer as well as an Embedding Layer from scratch.
Base your code on the following skeleton code that we provide:

### Exercise 1 - Character-based Tokenizer:
- Initialize your vocabulary with a list of unique characters. Consider alphabetic letters, common punctuation and numbers for a start. Your initial vocabulary should at least include lowercase English letters (a-z), digits (0-9), and common punctuation marks (e.g., ., !, ?).

- Implement a basic character-based tokenizer. Ensure to include a special $<UNK>$ ("unknown") token to handle characters outside your vocabulary.
  - The tokenizer should be capable of:
    - Parsing a string into a list of characters.
    - Encoding a list of characters into their corresponding indices in the vocabulary.
    - Decoding a list of indices back into a string.
    - When encoding, return the token ID for $<UNK>$ for any character not in the vocabulary. Similarly, when decoding, return the $<UNK>$ token for any unknown token ID.

In [1]:
# Importing necessary dependencies
from typing import List

In [5]:
vocab = list('') # define your vocabulary here

In [6]:
class Tokenizer:
    def __init__(self, vocab: List[str]):
        # Add <UNK> token if it's not already in the vocabulary
        pass # Replace "pass" with your own code

    def parse(self, input: str) -> List[str]:
        """Convert a string to a list of characters."""
        pass # Replace "pass" with your own code

    def encode(self, tokens: List[str]) -> List[int]:
        """ Encode a list of tokens into their corresponding indices."""
        pass # Replace "pass" with your own code

    def decode(self, indices: List[int]) -> str:
        """Decode a list of indices back into a string."""
        pass # Replace "pass" with your own code

### Run Exercise 1
Run this cell to evaluate your implementation.

In [19]:
"""
Expected Output:
============ Tokenizer
tokenizer.parse: ['c', 'a', 't', 'e', 'r', 'p', 'i', 'l', 'l', 'a', 'r', '!']
tokenizer.encode: [28, 26, 45, 30, 43, 41, 34, 37, 37, 26, 43, 53] # these numbers will be different
tokenizer.decode: caterpillar!
tokenizer.encode/decode unknown: <UNK> # This will be different if you choose to use a different <UNK> token
tokenizer.decode out of bounds: <UNK>  # This will be different if you choose to use a different <UNK> token
"""

tokenizer = Tokenizer(vocab)

print("============ Tokenizer")
# Test parsing
tokens = tokenizer.parse('caterpillar!')
print(f"tokenizer.parse: {tokens}")

# Test encoding
token_ids = tokenizer.encode(tokens)
print(f"tokenizer.encode: {token_ids}")

# Test decoding
print(f"tokenizer.decode: {tokenizer.decode(token_ids)}")

# Test <UNK>
print(f"tokenizer.encode/decode unknown: {tokenizer.decode(tokenizer.encode(['$']))}")
print(f"tokenizer.decode out of bounds: {tokenizer.decode([100])}\n")

============ Tokenizer
tokenizer.parse: ['c', 'a', 't', 'e', 'r', 'p', 'i', 'l', 'l', 'a', 'r', '!']
tokenizer.encode: [28, 26, 45, 30, 43, 41, 34, 37, 37, 26, 43, 53]
tokenizer.decode: caterpillar!
tokenizer.encode/decode unknown: <UNK>
tokenizer.decode out of bounds: <UNK>



### Excercise 2 -  Embedding Layer:
- Implement an embedding layer from scratch. This layer should be able to:
    - Initialize an embedding table with random values.
    - Look up and return embeddings for a given list of indices.
    - Handle potential out-of-bounds errors when looking up embeddings.

In [26]:
import torch
from torch import Tensor

In [27]:
class Embedding:
    def __init__(self, n_embd: int, d_embd: int):
        pass # Replace "pass" with your own code. You might use torch.randn

    def forward(self, input: Tensor) -> Tensor:
        """Perform a lookup for the given indices in the embedding table."""
        pass # Replace "pass" with your own code

    def __call__(self, input: Tensor) -> Tensor:
        # This function lets you call a class instance as a function e.g. Embedding(n_embd, d_emdb)(x)
        # https://docs.python.org/3/reference/datamodel.html#object.__call__
        return self.forward(input)

### Run Exercise 2
Run these cells to evaluate your implementation.

In [5]:
# A helper function to assert a function call throws an exception
def assert_raises(fn, *args, **kwargs):
    try:
        fn(*args, **kwargs)
    except Exception as e:
        print(f"Expected error occurred: {type(e).__name__} - {e}")
        return
    raise AssertionError("Expected error did not occur")

In [17]:
"""
Expected Output:

============ Embedding Layer
input (torch.Size([11])):
tensor([28, 26, 45, 30, 43, 41, 34, 37, 37, 26, 43]) # these numbers will be different

embedding_layer result (torch.Size([11, 3])):  # these numbers will be different, depending on your vocab size
tensor([[-0.0748,  0.5664, -0.6240], # all of the following numbers will be different and also different per run
        [-1.9658, -0.7646, -0.4583],
        [ 1.1624,  0.8075, -0.5995],
        [ 0.4513, -0.0109,  0.2278],
        [-1.2602, -0.8705, -0.0846],
        [ 0.3563,  0.4905,  0.5740],
        [ 0.5596,  0.3183, -2.2232],
        [-0.2117, -0.0676,  1.6243],
        [-0.2117, -0.0676,  1.6243],
        [-1.9658, -0.7646, -0.4583],
        [-1.2602, -0.8705, -0.0846]])
Expected error occurred: ValueError - Input tensor contains invalid indices for lookup table. # The string will depend on which error you throw
"""
print("============ Embedding Layer")
n_embd = len(vocab)
d_embd = 3
embedding_layer = Embedding(n_embd, d_embd)

input_tensor = torch.tensor(tokenizer.encode(tokenizer.parse('caterpillar')))
result = embedding_layer(input_tensor)

print(f"input ({input_tensor.size()}):\n{input_tensor}\n")
print(f"embedding_layer result ({result.size()}):\n{result}")

# Assure layer throws exception on invalid index
assert_raises(embedding_layer, torch.tensor([n_embd]))

============ Embedding Layer
input (torch.Size([11])):
tensor([28, 26, 45, 30, 43, 41, 34, 37, 37, 26, 43])

embedding_layer result (torch.Size([11, 3])):
tensor([[-0.8513,  0.9118, -1.2072],
        [ 0.3272,  1.3641,  1.9445],
        [ 0.9278,  0.8449, -1.0015],
        [-1.3227,  0.8415,  0.4359],
        [-0.3983,  0.0076, -0.0110],
        [-0.6541, -0.6403,  0.2624],
        [-0.6808, -1.1272, -0.9334],
        [ 1.0041,  0.1958,  1.0483],
        [ 1.0041,  0.1958,  1.0483],
        [ 0.3272,  1.3641,  1.9445],
        [-0.3983,  0.0076, -0.0110]])
Expected error occurred: ValueError - Input tensor contains invalid indices for lookup table.


# Example Solution
This will not be provided to the students.

In [1]:
import torch
from torch import Tensor
from typing import List

In [2]:
vocab = list("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz,!.;?")

In [3]:
class Tokenizer:
    def __init__(self, vocab: List[str]):
        # Ensure the '<UNK>' token is in the vocabulary
        if '<UNK>' not in vocab:
            vocab.append('<UNK>')

        self.vocab = vocab
        self.token2idx = {token: idx for idx, token in enumerate(vocab)}
        self.idx2token = {idx: token for idx, token in enumerate(vocab)}

    def parse(self, input: str) -> List[str]:
        """Convert a string to a list of characters."""
        return list(input)

    def encode(self, tokens: List[str]) -> List[int]:
        """Encode a list of tokens into their corresponding indices."""
        return [self.token2idx.get(token, self.token2idx.get('<UNK>', None)) for token in tokens]

    def decode(self, indices: List[int]) -> str:
        """Decode a list of indices back into a string."""
        return ''.join([self.idx2token.get(idx, '<UNK>') for idx in indices])

In [4]:
class Embedding:
    def __init__(self, n_embd: int, d_embd: int):
        self.lookup = torch.randn(n_embd, d_embd)

    def forward(self, input: Tensor) -> Tensor:
        """Perform a lookup for the given indices in the embedding table."""
        if input.max() >= self.lookup.size(0) or input.min() < 0:
            raise ValueError("Input tensor contains invalid indices for lookup table.")
        return self.lookup[input,:]
        
    def __call__(self, input: Tensor) -> Tensor:
        return self.forward(input)

In [5]:
# A helper function to assert a function call throws an exception
def assert_raises(fn, *args, **kwargs):
    try:
        fn(*args, **kwargs)
    except Exception as e:
        print(f"Expected error occurred: {type(e).__name__} - {e}")
        return
    raise AssertionError("Expected error did not occur")

In [6]:
tokenizer = Tokenizer(vocab)

print("============ Tokenizer")
# Test parsing
tokens = tokenizer.parse('caterpillar!')
print(f"tokenizer.parse: {tokens}")

# Test encoding
token_ids = tokenizer.encode(tokens)
print(f"tokenizer.encode: {token_ids}")

# Test decoding
print(f"tokenizer.decode: {tokenizer.decode(token_ids)}")

# Test <UNK>
print(f"tokenizer.encode/decode unknown: {tokenizer.decode(tokenizer.encode(['$']))}")
print(f"tokenizer.decode out of bounds: {tokenizer.decode([100])}\n")

# Test the embedding layer
print("============ Embedding Layer")

n_embd = len(vocab)
d_embd = 3
embedding_layer = Embedding(n_embd, d_embd)

input_tensor = torch.tensor(tokenizer.encode(tokenizer.parse('caterpillar')))
result = embedding_layer(input_tensor)

print(f"input ({input_tensor.size()}):\n{input_tensor}\n")
print(f"embedding_layer result ({result.size()}):\n{result}")

assert_raises(embedding_layer, torch.tensor([n_embd]))

============ Tokenizer
tokenizer.parse: ['c', 'a', 't', 'e', 'r', 'p', 'i', 'l', 'l', 'a', 'r', '!']
tokenizer.encode: [28, 26, 45, 30, 43, 41, 34, 37, 37, 26, 43, 53]
tokenizer.decode: caterpillar!
tokenizer.encode/decode unknown: <UNK>
tokenizer.decode out of bounds: <UNK>

============ Embedding Layer
input (torch.Size([11])):
tensor([28, 26, 45, 30, 43, 41, 34, 37, 37, 26, 43])

embedding_layer result (torch.Size([11, 3])):
tensor([[-1.9926,  0.9418, -0.1324],
        [-0.9731, -0.9792,  1.3101],
        [-0.8537,  0.9051,  0.8238],
        [ 0.0737,  1.0583,  1.4128],
        [-1.1847,  1.4029,  1.5147],
        [-1.0453,  0.2987, -0.7288],
        [-2.2460, -1.0628,  1.5335],
        [ 0.2482,  2.1593,  0.7753],
        [ 0.2482,  2.1593,  0.7753],
        [-0.9731, -0.9792,  1.3101],
        [-1.1847,  1.4029,  1.5147]])
Expected error occurred: ValueError - Input tensor contains invalid indices for lookup table.
